---
title: "STAT184-Final-project"
author: "Ariel"
date: "2024-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load packages
library(tidyr)
library(dplyr)
library(rvest)
#install.packages("readxl")
library(readxl)
#install.packages("openxlsx") 
library(openxlsx)
library(ggplot2)
```

```{r}
#Read data files

raw_data_total = read_excel('chronic-absenteeism-1.xlsx', sheet = 'Total')
raw_data_m = read_excel('chronic-absenteeism-1.xlsx', sheet = 'Male')
raw_data_f = read_excel('chronic-absenteeism-1.xlsx', sheet = 'Female')

```


```{R}
#x = raw_data_total
#data_T = as.data.frame(t(x[1:56,2:25]))

#row.names(data_T) = c(1:nrow(data_T))

#data_T = data_T[,-1]
#data_T[1,3] = 'Data_sort'
#data_T[2,3] = 'Number'

#names(data_T) = data_T[1,]
#data_T = data_T[-1,]

#Combine values in two columns
#for (i in 1:15) {
  #data_T[i,1] = data_T[i,2]
#}

#data_T = data_T[1:21,-2]
 #Remove number of schools reporting and their percentage, because we don't think subtle difference after 3rd digit matters

#names(data_T)[1] = 'Class_all' 
#data_T[1,1] = 'Total_student' #Fix missing values
#data_T = rbind(data_T[-1, ], data_T[1, ]) #Move the first total column to the last row

#rownames(data_T) = NULL

#data_clean = data_T %>%
  #fill(Class_all, .direction = "down") %>%
  #pivot_longer(
    #cols = -c('Class_all','Data_sort'),
    #names_to = 'State',
    #values_to = 'Value'
    #) %>%
  #pivot_wider(
    #names_from = 'Data_sort',
    #values_from = 'Value'
  #) %>%
  #mutate(across(Percent, ~ifelse(is.na(.), 100, .)))

#write.csv(data_clean, file = 'data_clean.csv', row.names = FALSE)
```

```{r}
#Write a function for above function, so it can be repeated on both female and male tables
clean_data_function = function(x = raw_data_total){
data_T = as.data.frame(t(x[1:56,2:25]))

row.names(data_T) = c(1:nrow(data_T))

data_T = data_T[,-1]
data_T[1,3] = 'Data_sort'
data_T[2,3] = 'Number'

names(data_T) = data_T[1,]
data_T = data_T[-1,]

#Combine values in two columns
for (i in 1:15) {
  data_T[i,1] = data_T[i,2]
}

data_T = data_T[1:21,-2]
 #Remove number of schools reporting and their percentage, because we don't think subtle difference after 3rd digit matters

names(data_T)[1] = 'Class_all' 
data_T[1,1] = 'Total_student' #Fix missing values
data_T = rbind(data_T[-1, ], data_T[1, ]) #Move the first total column to the last row

rownames(data_T) = NULL

data_clean = data_T %>%
  fill(Class_all, .direction = "down") %>%
  pivot_longer(
    cols = -c('Class_all','Data_sort'),
    names_to = 'State',
    values_to = 'Value'
    ) %>%
  pivot_wider(
    names_from = 'Data_sort',
    values_from = 'Value'
  ) %>%
  mutate(across(Percent, ~ifelse(is.na(.), 100, .)))

data_clean = data_clean[data_clean$Class_all != 'Students With Disabilities Served Under IDEA' & data_clean$Class_all != 'Students With Disabilities Served Only Under Section 504' & data_clean$Class_all != 'English Language Learners',]
return(data_clean)
}

```

```{r}
clean_total = clean_data_function(raw_data_total)
clean_f = clean_data_function(raw_data_f)
clean_m = clean_data_function(raw_data_m)

mutate_fun = function(x = clean_total){
  data_mttd = x %>%
    mutate(across(c(Class_all, State), factor)) %>%
    mutate(across(c(Number, Percent), as.numeric)) %>%
    mutate(across(everything(), ~replace_na(., 0)))
}

clean_total = mutate_fun(clean_total)
clean_f = mutate_fun(clean_f)
clean_m = mutate_fun(clean_m)

clean_total
clean_f
clean_m
```

```{r}
workbook = createWorkbook()

addWorksheet(workbook, "Total")
writeData(workbook, sheet = "Total", clean_total)

addWorksheet(workbook, "Female")
writeData(workbook, sheet = "Female", clean_f)

addWorksheet(workbook, "Male")
writeData(workbook, sheet = "Male", clean_m)

saveWorkbook(workbook, "data_clean.xlsx", overwrite = TRUE)
```

```{r, fig.width=10, fig.height=7}
#To see which group of students is likely to be absent, the absolute number is less meaningful, so we will mainly focus on percentage. And total data will be adjusted first using percentage in population as a baseline.

#Input data of every population group into a dataset
race_ratio = data.frame(
  Race = unique(clean_total$Class_all)[1:7],
  Percent = c(0.7, 5.9, 18.9, 12.6, 59.3, 0.2, 2.3)
)

data_US = clean_total[clean_total$State == 'United States',][1:7,]

data_US$Percent_adj = data_US$Percent/race_ratio$Percent
#The adjusted percentage greater than 1 means this group has bigger likelihood of absence, so we can get an overview

#Draw a bar chart
ggplot(data_US, aes(x = Class_all, y = Percent_adj, fill = Percent_adj > 1)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("dark green", "skyblue"), 
                    labels = c("Less Likely to be absent", "More Likely to be absent")) +  
  labs(title = "How many times greater a student is likely to absent more than 15 days than average level",
       x = "Races & Ethnicity", 
       y = "% in total absent students/\n% in total population") +
  geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 0.5) +  
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_text(angle = 0, vjust = 0.5))
#Asian has the lowest absent likelihood, then follows white people. All other groups of students are more likely to be absent.
```


```{r}
#Now we are going to look into every single race group
graph_fun = function(x = 'American Indian or Alaska Native', y = 10){
#Filter to get the Race we are about to analysis, Natives by default in this case
  data_all = clean_total[clean_total$Class_all == x,]
  data_f = clean_f[clean_total$Class_all == x,]
  data_m = clean_m[clean_total$Class_all == x,]
  
#Fill in values for sex column for future plot drawing  
  data_all$sex = rep('Total', nrow(data_all))
  data_f$sex = rep('female', nrow(data_f))
  data_m$sex = rep('male', nrow(data_m))
  
#Arrange datasets based on Percent, leave top 10 states, the number can also be altered by setting parameter y
   data_all = data_all %>% 
    arrange(desc(Percent)) %>%
    slice_head(n = y)
  data_f = data_f %>% 
    arrange(desc(Percent)) %>%
    slice_head(n = y)
  data_m = data_m %>% 
    arrange(desc(Percent)) %>%
    slice_head(n = y)
  
#Combine those three datasets  
  data = rbind(data_all, data_f, data_m)
  
#Set the sequence of top 10 states, or R will set them by the alphabet
  data$State <- factor(data$State, levels = unique(data$State))

#Draw the Bar chart using facet_wrap helper to put Total, Female & Male data in one harmonic plot
  plot = ggplot(data, aes(x = State, y = Percent, fill = sex)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ sex, scales = "free", nrow = 3) + 
#The parameter 'scales' enable different different arrangement of x value
  labs(title = paste("Top 10 states in Absent rate of", x),
       x = "State",
       y = "Absent Rate") +
  scale_fill_brewer(palette = "Set3")

#Return final value  
  return(plot)
}

```

```{r, fig.width=12, fig.height=7}
graph_fun(x = 'American Indian or\nAlaska Native')
```

```{r, fig.width=12, fig.height=7}
graph_fun(x = 'Asian')
```

```{r, fig.width=12, fig.height=7}
graph_fun(x = 'Hispanic or Latino of any race')
```

```{r, fig.width=12, fig.height=7}
graph_fun(x = 'Black or African American')
```

```{r, fig.width=12, fig.height=7}
graph_fun(x = 'White')
```

```{r, fig.width=12, fig.height=7}
graph_fun(x = 'Native Hawaiian or Other Pacific Islander')
```

```{r, fig.width=12, fig.height=7}
graph_fun(x = 'Two or more races')
```

```{r}
data_lm_f = clean_f[clean_f$Class_all != 'Total_student',]
data_lm_m = clean_m[clean_m$Class_all != 'Total_student',]

data_lm_f$sex = as.factor(rep('female', nrow(data_lm_f)))
data_lm_m$sex = as.factor(rep('male', nrow(data_lm_m)))
data_lm = rbind(data_lm_f, data_lm_m)

head(data_lm)
```

```{r}
lm_total_percent = lm(Percent ~ Class_all + State + sex, data = data_lm)

lm_total_number = lm(Number ~ Class_all + State + sex, data = data_lm)

summary(lm_total_percent)

summary(lm_total_number)
```

```{r}
lm_race_percent = lm(Percent ~ Class_all + sex, data = data_lm)

lm_race_number = lm(Number ~ Class_all + sex, data = data_lm)

summary(lm_race_percent)

summary(lm_race_number)

```

```{r}
scale

```

